language: java

services:
  - docker

jdk: oraclejdk8

dist: trusty

addons:
  apt:
    packages:
      - dpkg # this is required for fixing Travis' invalid chrome version issue
  chrome: stable

# env variables
# $RELEASE_BRANCH
# $GITHUB_TOKEN
# $ALLOWED_RELEASE_COMMITERS
# $SDK
git:
  submodules: false
before_install:
  - echo -e "\n\nmachine github.com\n  login $GITHUB_TOKEN\n" >~/.netrc
  - git submodule update --init --recursive
before_script:
  - export APPLITOOLS_REPORT_ID=${TRAVIS_COMMIT:0:7}-$TRAVIS_BUILD_NUMBER
  - echo "Travis tag is $TRAVIS_TAG"
  - echo "Travis event type is $TRAVIS_EVENT_TYPE"
  - if [[ "$TRAVIS_EVENT_TYPE" == "cron" || "$TRAVIS_TAG" =~ ^RELEASE_CANDIDATE ]]; then
    echo "Sandbox is false in test report";
    export APPLITOOLS_REPORT_TO_SANDBOX="false";
    echo "APPLITOOLS_REPORT_TO_SANDBOX=$APPLITOOLS_REPORT_TO_SANDBOX";
    fi
  - pushd eyes.selenium.java/src/main/node_resources
  - npm install
  - popd
jobs:
  include:
    - stage: Test
      name: Core
      script:
        - echo $APPLITOOLS_REPORT_ID
        - chmod +x ./runTests.sh
        - ./runTests.sh "eyes.sdk.core"
    - name: Images
      script:
        - echo $APPLITOOLS_REPORT_ID
        - chmod +x ./runTests.sh
        - ./runTests.sh "eyes.images.java"
    - name: Appium Android
      script:
        - echo $APPLITOOLS_REPORT_ID
        - sh upload_app.sh "https://applitools.bintray.com/Examples/android/1.3/app-debug.apk" "app_android"
        - sh upload_app.sh "https://applitools.bintray.com/Examples/androidx/1.1.0/app_androidx.apk" "app_androidx"
        - chmod +x ./runTests.sh
        - ./runTests.sh "eyes.appium.java"
    - name: Selenium
      script:
        - echo $APPLITOOLS_REPORT_ID
        - google-chrome --version
        - chromium-browser --version
        - latestChromeDriverURL=$(wget http://chromedriver.storage.googleapis.com/LATEST_RELEASE -q -O -)
        - wget "http://chromedriver.storage.googleapis.com/${latestChromeDriverURL}/chromedriver_linux64.zip"
        - unzip chromedriver_linux64.zip -d /home/travis/build/
        - chmod +x /home/travis/build/chromedriver
        - /home/travis/build/chromedriver --version
        - env webdriver.chrome.driver=/home/travis/build/
        - echo $TRAVIS_EVENT_TYPE
        - echo $TRAVIS_BRANCH
        - if [[ "$TRAVIS_EVENT_TYPE" == "cron" && "$TRAVIS_BRANCH" == "master" ]]; then
          sed -i 's/passedTestsSuite.xml/devTestsSuite.xml/g' $TRAVIS_BUILD_DIR/eyes.selenium.java/pom.xml;
          fi
        - chmod +x ./runTests.sh
        - ./runTests.sh "eyes.selenium.java"
        - chmod +x ./runConnectivityTests.sh
        - ./runConnectivityTests.sh
    - name: Selenium Mobile
      script:
        - echo APPLITOOLS_REPORT_ID
        - latestChromeDriverURL=$(wget http://chromedriver.storage.googleapis.com/LATEST_RELEASE -q -O -)
        - wget "http://chromedriver.storage.googleapis.com/${latestChromeDriverURL}/chromedriver_linux64.zip"
        - unzip chromedriver_linux64.zip -d /home/travis/build/
        - chmod +x /home/travis/build/chromedriver
        - /home/travis/build/chromedriver --version
        - env webdriver.chrome.driver=/home/travis/build/
        - sed -i 's/passedTestsSuite.xml/mobileTestsSuite.xml/g' $TRAVIS_BUILD_DIR/eyes.selenium.java/pom.xml;
        - chmod +x ./runTests.sh
        - ./runTests.sh "eyes.selenium.java"
    - name: Generic
      script:
        - echo APPLITOOLS_REPORT_ID
        - nvm install 14.5.0
        - nvm use 14.5.0
        - cd eyes.selenium.java;
        - if [[ $TRAVIS_TAG =~ ^RELEASE_CANDIDATE ]]; then
          yarn release;
          else
          yarn java;
          fi
    - stage: Test Appium IOS
      script:
        - echo APPLITOOLS_REPORT_ID
        - sh upload_app.sh "https://applitools.bintray.com/Examples/IOSTestApp/1.2/ipa/IOSTestApp.ipa" "app_ios"
        - sed -i 's/androidTestSuite.xml/iosTestSuite.xml/g' $TRAVIS_BUILD_DIR/eyes.appium.java/pom.xml;
        - chmod +x ./runTests.sh
        - ./runTests.sh "eyes.appium.java"
    - stage: Test Appium Failed
      if: env(TRAVIS_EVENT_TYPE) =~ ^cron$ AND branch = master
      script:
        - echo APPLITOOLS_REPORT_ID
        - sed -i 's/androidTestSuite.xml/failedTestSuite.xml/g' $TRAVIS_BUILD_DIR/eyes.appium.java/pom.xml;
        - chmod +x ./runTests.sh
        - ./runTests.sh "eyes.appium.java"
    - stage: Full Regression Mail
      if: env(TRAVIS_EVENT_TYPE) =~ ^cron$ AND branch = master
      script:
        - sh send_full_regression_mail.sh "$SDK"
    - stage: Deploy
      if: tag =~ ^RELEASE_CANDIDATE AND fork == false
      script:
          # save the email of the person who did this commit in COMMITTER_EMAIL
        - COMMITTER_EMAIL="$(git log -1 $TRAVIS_COMMIT --pretty="%cE")"
        - SDK_VERSION=$(echo $TRAVIS_TAG | sed 's/[^.0-9]*//g')
        - if [[ $COMMITTER_EMAIL =~ $ALLOWED_RELEASE_COMMITERS ]]; then
          echo "DEPLOY";
          chmod +x ./extractChangeLog.sh;
          TMP_CHANGELOG=$(./extractChangeLog.sh "$SDK_VERSION" "CHANGELOG.md");
          CHANGELOG=$([ -z "$TMP_CHANGELOG" ] && echo "There is no change log for version $SDK_VERSION"; echo "$TMP_CHANGELOG");
          echo $CHANGELOG;
          chmod +x ./sendMail.sh;
          TEST_COVERAGE_GAP=$(cat testCoverageGap.txt);
          ./sendMail.sh "$SDK" "$TRAVIS_TAG" "$CHANGELOG" "$TEST_COVERAGE_GAP";
          fi
